# XGBoost

## Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns 

## Importing the dataset

In [0]:
df=pd.read_csv('Placement_Data.csv', usecols=['sl_no','ssc_p','hsc_p','degree_p','etest_p','mba_p','status'])
df1 = pd.read_csv('Placement_Data.csv', usecols=['gender'])
df2 = pd.read_csv('Placement_Data.csv', usecols=['ssc_b'])
df3 = pd.read_csv('Placement_Data.csv', usecols=['hsc_s']) 
df4 = pd.read_csv('Placement_Data.csv', usecols=['degree_t']) 
df5 = pd.read_csv('Placement_Data.csv', usecols=['workex'])
df6 = pd.read_csv('Placement_Data.csv', usecols=['hsc_b'])

In [305]:
df.head()

sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p      status
0      1  67.00  91.00     58.00     55.0  58.80      Placed
1      2  79.33  78.33     77.48     86.5  66.28      Placed
2      3  65.00  68.00     64.00     75.0  57.80      Placed
3      4  56.00  52.00     52.00     66.0  59.43  Not Placed
4      5  85.80  73.60     73.30     96.8  55.50      Placed

In [306]:
#to know the no. of categories in dataframe
for col in df.columns :
     print(col,': ' , len(df[col].unique()), 'labels' )

sl_no :  215 labels
ssc_p :  103 labels
hsc_p :  97 labels
degree_p :  89 labels
etest_p :  100 labels
mba_p :  205 labels
status :  2 labels


In [307]:
#lets examin how many columns will be obtained after one hot encoding 
pd.get_dummies(df,drop_first=True).shape

(215, 7)

In [0]:
#lets find the top 10 most frequent categories for variables
df.hsc_s.values_count().sort_value(ascending=False).head(20)

In [343]:
df11=pd.get_dummies(df1['gender'],drop_first=True)
df12=pd.concat([df11,df1],axis=1)
df12.drop('gender',axis=1,inplace=True)
df12.head()

M
0  1
1  1
2  1
3  1
4  1

In [319]:
df21=pd.get_dummies(df2['ssc_b'],drop_first=True)
df22=pd.concat([df21,df2],axis=1)
df22.drop('ssc_b',axis=1,inplace=True)
df22.head()


Others
0       1
1       0
2       0
3       0
4       0

In [320]:
df31=pd.get_dummies(df3['hsc_s'],drop_first=True)
df32=pd.concat([df31,df3],axis=1)
df32.drop('hsc_s',axis=1,inplace=True)
df32.head()



Commerce  Science
0         1        0
1         0        1
2         0        0
3         0        1
4         1        0

In [333]:
df41=pd.get_dummies(df4['degree_t'],drop_first=True)
df42=pd.concat([df41,df4],axis=1)
df42.drop('degree_t',axis=1,inplace=True)
df43 = df42.rename(columns={'Others': 'degree_others'}, index={'ONE': 'one'})
df43.head()

degree_others  Sci&Tech
0              0         1
1              0         1
2              0         0
3              0         1
4              0         0

In [322]:
df51=pd.get_dummies(df5['workex'],drop_first=True)
df52=pd.concat([df51,df5],axis=1)
df52.drop('workex',axis=1,inplace=True)
df52.head()

Yes
0    0
1    1
2    0
3    0
4    0

In [323]:
df61=pd.get_dummies(df6['hsc_b'],drop_first=True)
df62=pd.concat([df61,df6],axis=1)
df62.drop('hsc_b',axis=1,inplace=True)
df63 = df62.rename(columns={'Others': 'hsc_b_others'}, index={'ONE': 'one'})
df63.head()

hsc_b_others
0             1
1             1
2             0
3             0
4             0

In [344]:
df7=pd.concat([df63,df52,df43,df32,df22,df12,df],axis=1)
df7.head()

hsc_b_others  Yes  degree_others  ...  etest_p  mba_p      status
0             1    0              0  ...     55.0  58.80      Placed
1             1    1              0  ...     86.5  66.28      Placed
2             0    0              0  ...     75.0  57.80      Placed
3             0    0              0  ...     66.0  59.43  Not Placed
4             0    0              0  ...     96.8  55.50      Placed

[5 rows x 15 columns]

In [346]:
df71=pd.get_dummies(df7['status'],drop_first=True)
dataset=pd.concat([df71,df7],axis=1)
dataset.drop('status',axis=1,inplace=True)
dataset.head()

Placed  hsc_b_others  Yes  degree_others  ...  hsc_p  degree_p  etest_p  mba_p
0       1             1    0              0  ...  91.00     58.00     55.0  58.80
1       1             1    1              0  ...  78.33     77.48     86.5  66.28
2       1             0    0              0  ...  68.00     64.00     75.0  57.80
3       0             0    0              0  ...  52.00     52.00     66.0  59.43
4       1             0    0              0  ...  73.60     73.30     96.8  55.50

[5 rows x 15 columns]

In [351]:
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, -2].values

x=X
print(x)
x.shape

[[ 1.    0.    0.   ... 58.   55.   58.8 ]
 [ 1.    1.    0.   ... 77.48 86.5  66.28]
 [ 0.    0.    0.   ... 64.   75.   57.8 ]
 ...
 [ 1.    1.    0.   ... 73.   59.   69.72]
 [ 1.    0.    0.   ... 58.   70.   60.23]
 [ 1.    0.    0.   ... 53.   89.   60.22]]


(215, 14)

In [352]:
print(x)

[[ 1.    0.    0.   ... 58.   55.   58.8 ]
 [ 1.    1.    0.   ... 77.48 86.5  66.28]
 [ 0.    0.    0.   ... 64.   75.   57.8 ]
 ...
 [ 1.    1.    0.   ... 73.   59.   69.72]
 [ 1.    0.    0.   ... 58.   70.   60.23]
 [ 1.    0.    0.   ... 53.   89.   60.22]]


## Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## Training XGBoost on the Training set

In [362]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

## Making the Confusion Matrix

In [363]:
y_pred=classifier.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6517000422485586

In [366]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

ValueError: ignored

## Applying k-Fold Cross Validation

In [0]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))